version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/cryptographic-message-syntax"
      - "/pgp-cleartext"
      - "/x509-certificate"
    schedule:
      interval: "weekly"
    commit-message:
      commit-message: "workspace: "
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci: "
